name: issue
on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited, deleted]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Download sdk
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output
        with:
         url: "http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/apache-royale-0.9.8-bin-js.zip"
         target: sdk/ 
      - name: tar 
        id: tar
        run: |
          cd sdk
          attrib 'apache-royale-0.9.8-bin-js.zip'
          tar -x -f 'apache-royale-0.9.8-bin-js.zip'
          cd ..
          cd gh-pages
          if(Test-Path ${{ github.event.issue.id }}){}else{mkdir ${{ github.event.issue.id }}} 
          cd ${{ github.event.issue.id }}
          if(Test-Path ${{ github.event.comment.id }}){}else{mkdir ${{ github.event.comment.id }}} 
          cd ${{ github.event.comment.id }}
          echo ${{ github.event.comment.body }} >${{ github.event.comment.id }}.js
          
          
          uses: DamianReeves/write-file-action
           with:
            path: gh-pages/${{ github.event.issue.id }}/${{ github.event.comment.id }/test.js
             contents: |
              ${{ github.event.comment.body }}
           write-mode: overwrite
          dir
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
