name: issue
on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited, deleted]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Download sdk
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output
        with:
         url: "http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/apache-royale-0.9.8-bin-js.zip"
         target: sdk/ 
      - name: tar 
        id: tar
        run: |
          $rootpath=$(get-location).path
          $sdk=$rootpath+"/sdk/royale-asjs"
          $thirdParty=$rootpath+"/examples\thirdParty"
          cd sdk
          tar -x -f 'apache-royale-0.9.8-bin-js.zip'
          cd ..
          cd gh-pages
          cd auto
          python main.py
          $className = Get-Content ${{ github.event.comment.id }}/main.txt -Raw
          echo className=$className
          ..\..\sdk\royale-asjs/js/bin/asjsc.bat ${{ github.event.comment.id }}\$className.as -js-output-optimization=skipAsCoercions -library-path+=$sdk\frameworks\js\libs\CoreJS.swc -library-path+=$sdk\frameworks\js\libs\XMLJS.swc -library-path+=$sdk\js\libs\js.swc  -source-path+=$rootpath\src -source-path+=${{ github.event.comment.id }} -source-path+=$thirdParty\adobe -source-path+=$thirdParty\box2dflash -source-path+=$thirdParty\MornUILib\src -source-path+=$thirdParty\protebuff -source-path+=$thirdParty\utils -source-path+=$thirdParty\MornUIDemo\src -source-path+=$thirdParty\MinimalComps_0_9_10 -warn-public-vars=false -remove-circulars=true -js-compiler-option+='--compilation_level ADVANCED_OPTIMIZATIONS' -targets=JSRoyale -define=CONFIG::as_only,false -define=CONFIG::js_only,true -define=COMPILE::JS,true -warnings=false
          ..\..\sdk\royale-asjs/js/bin/asjsc.bat ${{ github.event.comment.id }}\$className.as -js-output-optimization=skipAsCoercions -source-path+=.\..\..\src -source-path+=${{ github.event.comment.id }} -warn-public-vars=false -remove-circulars=true -targets=JSRoyale -define=CONFIG::as_only,false -define=CONFIG::js_only,true -define=COMPILE::JS,true -warnings=false
          cd ..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
